gongmyeong-study/orangenongjang

draft-project/public/index.html
draft-project/src/components/main/main.css
draft-project/src/components/main/main.tsx
draft-project/src/index.tsx

1. HTML template created - main.tsx
2. CSS for main.tsx created- main.css
3. index page <title> modified : "React App" -> "공명 개발 스터디"

Main page UI created

---

.github/workflows/django.yml
nongjang/board/serializers.py
nongjang/nongjang/settings.py

- 개발에서는 test를 통한 [CI(지속적 통합)](https://ko.wikipedia.org/wiki/지속적_통합)도 매우 중요합니다.
- 앞으로 개발을 하면서 실제 동작하는 코드뿐 아니라, 내 코드에 대한 test도 짜나갈 것입니다. 차차 더 얘기하도록 하죠.
* * *

Applying GitHub Actions

---

nongjang/necessity/serializers.py
nongjang/necessity/views.py

* 변경 전 : user와 necessity 정보 리턴 시 username과 necessityname만 리턴
* 변경 후 : user id, user name 그리고 , necessity id, necessity 리턴
GET /api/v1/necessity/log/

modify log serializer

---

orange/package.json
orange/yarn.lock

* precommit 기능을 위해 husky를 추가했습니다. 이제 eslint는 commit 시 자동 적용이 됩니다.
* eslint 이외에도 precommit / prepush에 넣을 스크립트가 필요하면 추가하면 됩니다.
https://github.com/typicode/husky/tree/master

ON-22 [front] add husky to use precommit

---

orange/src/containers/TimelinePage/TimelinePage.tsx

[ON-26](https://orangenongjang.atlassian.net/browse/ON-26) : [ON-13](https://orangenongjang.atlassian.net/browse/ON-13)에서 대규모로 수정한 API를 반영하였습니다.
<br>

ON-26 [front] Connect Necessity Log API to Web Frontend

---

nongjang/house/serializers.py
nongjang/house/views.py
orange/src/containers/HousePage/HousePage.tsx

related issues: https://orangenongjang.atlassian.net/browse/ON-55
* * *
- <img width="434" alt="스크린샷 2020-12-06 23 54 08" src="https://user-images.githubusercontent.com/35535636/101283538-57508080-381e-11eb-912f-90b765e55fa0.png">
- <img width="1779" alt="스크린샷 2020-12-06 23 57 39" src="https://user-images.githubusercontent.com/35535636/101283613-d47bf580-381e-11eb-8bb4-83d8adab3ab9.png">

ON-55 [back] House 수정 및 삭제(leader) API 개발

---

.gitattributes

related docs
- https://github.com/github/linguist#my-repository-isnt-showing-my-language
- https://medium.com/@bolajiayodeji/introducing-github-linguist-8f09273ddea1
- https://musma.github.io/2019/08/26/github-linguist-overrides.html

mark build files as linguist-vendored

---

nongjang/user/views.py

- https://github.com/gongmyeong-study/orangenongjang/pull/81/files/0b56ccede3ae3ca53f0baedea57bc1f60c653995#r546241391 에서 언급한 내용이 기반.
- [Jira ON-61](https://orangenongjang.atlassian.net/browse/ON-61)
<br>
<br>
- #81 에서와 마찬가지로 불필요한 `try ~ except KeyError:` 삭제함

ON-61 [back] 회원가입 인증 시 발생할 수 있는 에러 제거

---

orange/public/index.html

ON-82 [front] font 적용 안되는 문제 해결

---

orange/src/containers/NecessityPage/NecessityPage.tsx

> [Jira ON-44](https://orangenongjang.atlassian.net/browse/ON-44)
- House 내부로 진입했을 때, "집집" 대신 진짜 House 이름이 보이도록 수정
<br>

ON-44 [front] House 내부 페이지에서 집 이름을 반영하기

---

orange/src/components/Necessity/NecessityRemoveButton/NecessityRemoveButton.tsx
orange/src/components/Necessity/NecessityUpdateButton/NecessityUpdateButton.css
orange/src/components/Necessity/NecessityUpdateButton/NecessityUpdateButton.tsx

> Jira [ON-98](https://orangenongjang.atlassian.net/browse/ON-98?atlOrigin=eyJpIjoiYmFhNzBmNTAyNjRmNGQ5N2FlMWE0ODM0MGMxOWYzZGYiLCJwIjoiaiJ9)
<br>
- Necessity box 내부 '수정' 및 '삭제' 버튼 pointer 변경
> 단순히 cursor를 pointer로 변경하는 작업이기 때문에 굳이 css 파일을 생성하지는 않았습니다.

ON-98 [front] Necessity box 내부 '수정' 및 '삭제' 버튼 pointer 변경

---

orange/src/components/Header/Header.css
orange/src/components/Header/Header.tsx

ON-68 [front] 모바일 뷰에서 Navbar 햄버거 & 로고 넣기

---

orange/src/components/House/HouseManageModal/HouseManageModal.css
orange/src/components/House/HouseManageModal/HouseManageModal.tsx

> Jira [ON-102](https://orangenongjang.atlassian.net/browse/ON-102)
- House Leader Toss를 위한 멤버 드롭다운 창 크기 변경
- 각종 css 설정 변경
<br>

ON-102 [front] House Leader Toss를 위한 멤버 드롭다운 창 크기 변경

---

nongjang/house/paginations.py
nongjang/house/views.py
orange/src/api/necessity.ts
orange/src/containers/TimelinePage/TimelinePage.tsx

related issues: https://orangenongjang.atlassian.net/browse/ON-50, https://orangenongjang.atlassian.net/browse/ON-51
- scroll이 중간쯤 내려가면 20개씩 다음 NecessityLog 가져오도록 수정
- 여기는 class component 방식으로 미개척지던데... 그냥 있던대로 짰음

ON-50, ON-51 NecessityLog에 pagination 적용하기

---

orange/src/components/Header/Header.css
orange/src/containers/HousePage/HousePage.scss

아이폰 사파리에서 관리, 초대 버튼이 깨지는 이슈를 해결했습니다.
- 버튼의 height, width가 rem으로 되어 있던 것을 padding을 rem으로 주는 방식으로 해결
- right info가 absolute로 되어 있는 것을 고침
그 외 navbar 위치가 폰마다 다른 이슈를 해결했습니다 (padding 0 줌)

ON-100 [front] : House Page 디자인 이슈 해결

---

orange/src/components/Necessity/NecessityItem/NecessityItem.css
orange/src/components/Necessity/NecessityList/NecessityList.css
orange/src/components/Necessity/NecessityList/NecessityList.tsx
orange/src/components/PlaceBox/PlaceBox.css
orange/src/components/PlaceBox/PlaceBox.tsx
orange/src/components/PlaceCreateForm/PlaceCreateForm.css
orange/src/containers/HousePage/HousePage.tsx
orange/src/containers/MainPage/MainPage.css
orange/src/containers/MainPage/MainPage.tsx
orange/src/containers/NecessityPage/NecessityPage.css
orange/src/containers/NecessityPage/NecessityPage.tsx

모바일 / 데스크탑에서 꺠지는 이슈 해결
디자인 고도화.

ON-93, 94, 95, 103 [front] Necessity page 디자인 고도화

---

orange/src/containers/InfoPage/InfoPage.tsx

related issues: https://orangenongjang.atlassian.net/browse/ON-107

ON-107 소개 페이지에서 사람 순서 랜덤하게 노출되게 하기

---

orange/src/containers/InfoPage/InfoPage.css
orange/src/containers/InfoPage/InfoPage.tsx

> Jira [ON-76](https://orangenongjang.atlassian.net/browse/ON-76)
- 오렌지농장 소개 문구를 Info Page 상단에 배치
- 웹프론트 : 
<br>
- 모바일프론트 : 
<br>

ON-76 [front] 오렌지농장 소개 문구 작성

---

orange/src/components/LogList/LogList.css
orange/src/components/LogList/LogList.scss
orange/src/components/LogList/LogList.tsx
orange/src/containers/TimelinePage/TimelinePage.css
orange/src/containers/TimelinePage/TimelinePage.tsx

라이브러리 컴포넌트로 되어있어서 css를 억지로 맞추긴 했습니다

ON-111 [front] Timeline page 디자인 이슈 해결

---

orange/src/components/Header/Header.css
orange/src/components/Header/Header.tsx
orange/src/containers/HousePage/HousePage.scss

ON-114, 115 [front] header 수정 - '집 목록' 버튼 추가

---

orange/src/components/Header/Header.css
orange/src/components/Header/Header.tsx
orange/src/components/LogList/LogList.scss
orange/src/containers/TimelinePage/TimelinePage.css

ON-117, 118 [front] timeline 너비 넓히기 & header 조정

---

orange/src/components/House/HouseInviteModal/HouseInviteModal.tsx
orange/src/components/House/HouseManageModal/HouseManageModal.css
orange/src/components/House/HouseManageModal/HouseManageModal.tsx
orange/src/containers/HousePage/HousePage.scss

> Jira [ON-116](https://orangenongjang.atlassian.net/browse/ON-116)
- 가입 날짜 표시인 물결표시(~)가 오른쪽이 아닌 왼쪽으로 잘못 배치된 것 수정하기
- House Leader 양도를 위한 멤버 선택 드롭다운 창 수정하기
- Galaxy S10 5G 기종 등에서 House 초대 이메일 전송 버튼이 아래쪽으로 내려오는 현상 수정 (Input 오른쪽 마진 약간 줄이기)
- House 이름이 긴 경우 House Manage/Invite CloseModal 버튼이  (특히 모바일에서) House 이름과 가깝게 보이는 현상 수정

ON-116 [front] House Modal 수정

---

orange/src/containers/MainPage/MainPage.scss

ON-129 [front] fix css height on mobile timeline page

---

nginx-app.conf
nongjang/nongjang/settings.py
nongjang/requirements.txt

related issues: https://orangenongjang.atlassian.net/browse/ON-65

ON-65 [infra] Django static 배포 처리하기

---

nongjang/house/admin.py
nongjang/house/models.py
nongjang/necessity/admin.py
nongjang/necessity/models.py

HouseAdmin
PlaceAdmin
NecessityAdmin

Django admin basic

---

orange/src/containers/InfoPage/InfoPage.tsx

> Jira [ON-133](https://orangenongjang.atlassian.net/browse/ON-133)
- InfoPage에 종은이에게 바치는 감사의 인사 추가하기
> `Special Thanks to 종은 for designing Logos`

ON-133 [front] Logo 디자이너(종은) 감사의 말 추가하기

---

README.md

- Django `3.0.7` -> `3.11.6`
- DRF `3.11.0` -> `3.11.2`

Change badge version in README
