gongmyeong-study/orangenongjang

orange/src/components/Articles/Articles.tsx, orange/src/components/Header/Header.tsx, orange/src/components/StudyInfo/StudyInfo.tsx
- 6.28.(일) 모임 이후 이 페이지를 본격적으로 새롭게 활용할 예정이므로, 기존 내용을 정리합니다.
- 기존 Main Page의 article 내용들을 삭제합니다.
- 스터디 멤버의 상황을 업데이트합니다.
=> Main Page 정리

nongjang/nongjang/settings.py
- **note: 기본적으로 Linux 또는 MacOS 기준으로 설명하므로, Windows에서는 약간 다른 command가 필요할 수도 있습니다.**
- dev는 개발 환경(지금은 이것이 즉 로컬 환경이지만, 개발 db도 AWS RDS 등으로 원격으로 따로 두는 경우도 많습니다), prod는 실제 서비스(production) 환경을 뜻합니다.
- `python manage.py runserver` 또는 `MODE=dev python manage.py runserver`와 같은 식으로 Django 서버를 실행하면 로컬 MySQL db에 연결합니다. AWS RDS에 연결하기 위해서는 `MODE=prod python manage.py runserver`로 환경 변수에 prod를 두어 서버를 실행합니다.
- 로컬 MySQL에 적절한 password를 가진 user 정보와, 적절한 이름을 가진 database, 그리고 user가 그것에 대한 권한을 가져야 합니다.
- MySQL 서버가 실행되는 상태임을 확실히 하세요.
`mysql.server start`
- 로컬 MySQL cli에 접속하세요. 기본적으로 password가 없는 root 라는 계정이 존재할 가능성이 높습니다.
`mysql -u root`
- 아래 명령어는 MySQL cli에서 실행하는 명령입니다. username, password, dbname은 AWS RDS의 그것과 같습니다. 즉, `secret_info.json`과 같은 값들을 사용하면 됩니다. 아래 command에 그것들을 포함시키는 것은 보안 이슈가 있으므로 `{DATABASE_NAME}` …
=> local db & cache setting

orange/src/components/LogList/LogList.tsx, orange/src/components/index.tsx, orange/src/constants/constants.ts, orange/src/containers/MainPage/MainPage.tsx, orange/src/containers/TimelinePage/TimelinePage.tsx
* redux를 끼지 않고 componentDidMount에서 호출합니다.
* api 호출 성공 시 response를 전달하여 <LogList /> 를 리턴합니다.
* " 'user'가 'necessity'를 'activfity_category'했습니다. ('created_at') " 와 같은 형식으로 표시합니다.
* created_at의 값을 toLocaleString()로 변형하여 시간 표시 형태가 못생긴 상태입니다. log 스타일을 꾸밀 때 date 스타일도 변경할 예정입니다.
* css를 넣지 않은 상태입니다.
=> Add log to Timeline page (no css)

nongjang/necessity/views.py
참고 : [**Jira ON-12**](https://orangenongjang.atlassian.net/browse/ON-12)
**생필품 수정 기능**
- Necessity Update API([Jira ON-4](https://orangenongjang.atlassian.net/browse/ON-4))에 존재하던 오류 수정
> 기존에는 Necessity Table과 비교하여 중복된 생필품인지 아닌지를 체크했으나 이제는 NecessityUser table의 **necessity_id**와 새롭게 생성되거나 기존에 존재하여 호출된 necessity_new의 **id**를 비교하는 방식을 사용함.
> NecessityUser table에 존재하는 생필품으로 수정하려고 할 때 발생하는 IntegrityError를 **409 Conflict** status code로 처리하여 `'error': "이미 존재하는 생필품입니다."`를 반환하도록 변경함.
=> ON-12 [back] Necessity Update API debugging

orange/src/App.tsx, orange/src/components/HouseList/HouseList.tsx, orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx, orange/src/components/index.tsx, orange/src/containers/HousePage/HousePage.tsx, orange/src/containers/MainPage/MainPage.tsx, orange/src/containers/NecessityPage/NecessityPage.tsx, orange/src/containers/TimelinePage/TimelinePage.tsx, orange/src/containers/index.tsx, orange/src/store/actions/necessity/necessity.tsx
* 유저의 하우스 목록을 불러옵니다
* 버튼을 누르면 해당 하우스 id를 들고 main으로 이동합니다
*  '/' route를 MainPage에서 HousePage로 변경했습니다
* 메인 페이지는 '/main/:id' 로 url이 변경되었습니다
* 유저의 house가 아닐 경우 /main 에서 다른 페이지(/house 같은)로 이동 시켜야 함
* 하우스 만들기 버튼을 넣어야 함 
현재 하우스 만드는 버튼이 없기 때문에 포스트맨으로 직접 House 만든 후 테스트 부탁드립니다
=> ON-15 [front] HousePage & API request with house id

nongjang/house/views.py
[Jira ON-20](https://orangenongjang.atlassian.net/browse/ON-20)에 명시한대로 Django code 두 줄 수정하였습니다.
현재 Main branch에서는 생필품 생성 시 [NecessityCreateModal.tsx](https://github.com/gongmyeong-study/orangenongjang/blob/master/orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx#L116)에서 price 및 count input 값을 다음과 같이 정의하고 있습니다.
이는 프론트엔드에서 price 값으로 1234.5 등의 값을 입력해도 정수로 내림하여 반환하는 함수를 사용한 코드로서, 오류가 있는 상황이기 때문에 추후 [ON-19](https://orangenongjang.atlassian.net/browse/ON-19)에서는 지금의 **parseInt** 대신 **parseFloat**을 사용할 예정입니다. parseFloat을 사용하면 사용자가 1234.5 값을 입력했을 때 백엔드에서 `isinstance(price, int)`를 통해 "**price는 0 이상의 정수여야 합니다.**"라는 문구와 함께 **400 Error**를 반환하게 됩니다.
=> ON-20 [back] Change logic of validating count and price variable

nongjang/house/serializers.py, nongjang/house/urls.py, nongjang/house/views.py, nongjang/necessity/serializers.py, nongjang/necessity/urls.py, nongjang/necessity/views.py
- necessity/views.py에서 관리되던 (user들의) 생필품 생성 및 수정, 수량 증감 API를 house/views.py에서 담당하도록 수정하였습니다. 이에 따라 새로운 url을 정의할 필요가 있어 기존의  GenericViewSet 대신 개별 APIView를 override했기 때문에 get_object, get_serializer 등의 함수를 상속할 수 없게 됩니다.
- [PUT, DELETE] `/api/v1/necessity_house/{necessity_house_id}/ `
-> [PUT, DELETE] `/api/v1/house/{house_id}/necessity/{necessity_id}/`
- [PUT] `/api/v1/necessity_house/{necessity_house_id}/count/`
-> [PUT] `/api/v1/house/{house_id}/necessity/{necessity_id}/count/`
<br>
- [ON-20](https://github.com/gongmyeong-study/orangenongjang/pull/49)에서 count 및 price가 str인 경우(postman을 통해 직접 API를 시행시키는 경우)와 int인 경우(frontend에서 값을 정수로 제한하여 backend로 보낸 경우) 모두를 고려한 코드를 바탕으로 생필품 수정 및 수량 증감 API 코드를 개선하였습니다.
=> ON-23 [back] modify urls for creating and updating necessity API

nongjang/house/serializers.py, nongjang/house/views.py
- [GET] `/api/v1/house/{house_id}/necessity_log/ `
- 생필품 수량 변경 시 Log 생성
- NecessityLog 정렬 방식에 기존의 '최신순'에 '사용자순'을 추가하여 사용자의 이름을 오름차순으로 하여 생필품 관리 기록을 확인 가능.
<br>
- [GET] `/api/v1/house/{houseId}/necessity/`
- 생필품 나열 순서를 기존의 '변경순'에서 '최신순', '이름순'으로 변경함.
<br>
- [ON-9](https://orangenongjang.atlassian.net/browse/ON-9) 바로 작업 시작할 예정.
=> ON-8 [back] Ordering for NecessityList & NecessityLog API

nongjang/house/serializers.py, nongjang/house/views.py, orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx, orange/src/store/reducers/necessity/necessity.tsx
related issues: https://orangenongjang.atlassian.net/browse/ON-31, https://orangenongjang.atlassian.net/browse/ON-25
- count 0인 상태인 NecessityHouse가 존재하도록 변경 (특정 생필품이 다 떨어진 순간 등)
- 삭제를 하면 NecessityHouse 해당 row가 실제로 삭제됨
- `DELETE /api/v1/house/{house_id}/necessity/{necessity_id}/` 의 response를 `GET /api/v1/house/{house_id}/necessity/` 와 동일한 형태로 삭제 이후의 해당 집 생필품들의 list를 포함하도록 함
- 이에 관련한 React reducer 관련 한 줄 수정
* * *
- `POST /api/v1/house/{house_id}/necessity/` 에서, frontend가 DB에 기 존재하는 생필품으로 요청하려는 경우 해당 necessity_id를 전달해야 함.
- 그러나 ON-25 작업 전까지, frontend가 NecessityHouse의 Necessity로서 택하고 싶은 necessity_id를 알 방법이 없음. 따라서 그 전까지 임시 방편인 조치를 취하고 FIXME로 표시함.
=> ON-31 [back] count 0과 삭제를 유저 입장에서 분리

orange/src/components/LogList/LogList.tsx
- 어떤 Action이든 상관 없이 모두 switch case의 default인 "를(을) 수정하였습니다."로 타던 기존의 방식을 수정. (props.logs.action_category가 아닌 props.logs.action로 변경)
- NecessityCount 수행 시 action을 추가했습니다.
<br>
- "를(을)" 조사 대신 "을(를)"로 바꾸었습니다.
=> ON-30 [front] Fix a bug about NecessityLog and make it grammatically natural 

orange/package.json, orange/src/App.tsx, orange/src/components/Login/Login.tsx, orange/src/components/SignUpModal/SignUpModal.tsx, orange/src/containers/IntroPage/IntroPage.tsx, orange/yarn.lock
* form ui는 material ui로, validtaion은 react-hook-form으로 하도록 로그인, 회원가입 컴포넌트를 변경했습니다
* redux 연결을 react redux hook 방식으로 하는 등 함수형 컴포넌트에 맞게 hook 방식으로 수정했습니다
* 발목을 잡던게 dispatch 호출로 변경된 state에 따라 history.push하는 부분이었는데, useEffect 안이나 바깥에 넣으면 무한루프가 발생합니다. 임시방편으로 push가 아닌 reload로 처리했는데, 나중에 세련된 방법으로 수정하겠습니다. (history.push할 때 route state가 바뀌는걸 잘 잡으면 될 것 같은데..) 
*이 PR에서는 디자인이 아닌 기능 변화를 담았습니다. form과 hook을 사용하는 예제가 되길 바랍니다
*create necessity에도 새로운 form을 도입하려고 했는데, 생각보다 리팩토링할 부분이 많이 보여서 디자인 작업하면서 다 뜯어고쳐야 할 것 같습니다
=> ON-28 [front] material ui form with hook

nongjang/user/text.py, nongjang/user/views.py
[Jira ON-43](https://orangenongjang.atlassian.net/browse/ON-43)
- 회원가입 시 가입한 이메일로 회원인증링크가 전송되지만 # GET /api/v1/user/{uidb64}/activate/{token}/가 동작하지 않아 is_active가 False에서 True로 변하지 않는 에러를 수정함.
- prod 및 dev 환경 모두에서 링크가 메일을 통해 전송되며, 링크 클릭 시 is_active가 True로 바뀜을 확인했습니다.
- 링크 클릭 후 회원 인증이 완료되면 `https://orangenongjang.com/main/`로 redirect됩니다.
=> ON-43 [back] Fix url and add redirection

nongjang/necessity/serializers.py, orange/src/api/necessity.ts, orange/src/components/LogList/LogList.tsx
- place를 새로 생성할 수 있게 되면서 NecessityLog가 기록되는 **타임라인**에도 place 이름을 명시하라 필요가 생김.
<br>
<br>
- CREATE / UPDATE / DELETE / COUNT 각 행위에 따라 한국어 조사('을/를', '이/가' 등)가 필요하던 기존의 방식에서 조사가 필요하지 않도록 축약함.
- 행위자의 이름을 괄호에 넣는 방식 대신 'by 고영현'으로 수정.
- Log 문장의 크기를 한 단계 키움.
=> ON-47 [back/front] 타임라인에서 place 이름을 보여주도록 수정

nongjang/user/views.py, orange/src/containers/IntroPage/IntroPage.tsx
> check_password 함수를 사용하여 username, password를 잘 입력한 미인증 회원에게는 HTTP_401_UNAUTHORIZED 에러 반환.
<br>
<br>
<br>
- 각종 주석 제거
- 회원가입 인증 링크 클릭 시 response를 렌더링하는 front 페이지가 없는 상태이므로 굳이 user response를 반환하지 않고 바로 로그인 페이지로 redirect하도록 수정. (기존에는 serializer 이전의 redirect 기능이 작동하지 않던 상태)
=> ON-52 [back/front] 로그인 시 미인증 회원에게 인증이 필요하다고 알리는 기능 수정

Jenkinsfile, nongjang/house/text.py, nongjang/house/urls.py, nongjang/house/views.py
[Jira ON-53](https://orangenongjang.atlassian.net/browse/ON-53)
- 회원가입 직후 미인증된 회원을 House에 초대할 때 401 error로 대응
- 이미 활동중인 멤버를 House에 초대할 때 409 error로 대응 (`def invitation`)
> activation link를 조작하는 등 부정한 방법으로 이미 활동중인 멤버가 다시금 userHouse에 초대될 때 발생하는 integrityError를 막기 위해 `def activate`에서도 409 error로 대응
<br>
- <img width="705" alt="image" src="https://user-images.githubusercontent.com/46114393/102386982-2b4db000-4013-11eb-9266-4f41ff8925dc.png">
=> ON-53 [back] House 초대 이메일 인증 API

Dockerrun.aws.json, docker-compose.yaml, nginx-app.conf, nongjang/Dockerfile, nongjang/nongjang/settings.py
Reverts gongmyeong-study/orangenongjang#88
Docker build 단계에서 collectstatic 하려면 Secrets Manager 때문에 AWS credentials가 필요한데, 이를 건네주는 방식에 대한 고민이 필요함.
=> Revert "deploying django static files"

orange/src/components/PlaceBox/PlaceBox.css, orange/src/components/PlaceBox/PlaceBox.tsx
> [Jira ON-70](https://orangenongjang.atlassian.net/browse/ON-70)
- chrome에서 pencil 모양의 icon이 보이지 않던 현상을 수정
<br>
- input box의 크기가 Place name에 비해 작아 수정 시에 부자연스럽게 보이던 현상을 수정
- input text 및 placeholder 길이에 맞추어 input box width 조절
<br>
=> ON-70 [front] Place 이름 수정 button 꾸미기 및 image 교체

nongjang/house/text.py, nongjang/house/views.py, nongjang/user/text.py, nongjang/user/views.py
> [Jira ON-85](https://orangenongjang.atlassian.net/browse/ON-85)
- `build_absolute_uri() will always generate an absolute URI with the same scheme the current request has.` 참고하여 user 및 house text.py의 link에 **http** 또는 **https** 명시를 하지 않도록 수정함
<br>
- House 초대장의 어투, 형식을 맞추어 통일성 제고
<br>
<br>
참고 : [django docs](https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.build_absolute_uri)
=> ON-85 [back] 회원인증 및 House 초대장 메일 링크가 http인 부분 수정

orange/src/components/Header/Header.css, orange/src/containers/HousePage/HousePage.scss, orange/src/containers/IntroPage/IntroPage.scss, orange/src/containers/MainPage/MainPage.css
각종 컴포넌트( 로그인&회원가입 클릭 / house 입장&관리&초대 클릭 /  main 탭 4개 ) css에 `cursor: pointer`를 추가하여 사용자들로 하여금 커서 위치가 클릭가능한 곳임을 알게 됩니다.
=> ON-71 [front] 클릭할 수 있는 컴포넌트 커서 변경

nongjang/house/text.py, nongjang/house/views.py, nongjang/user/text.py, nongjang/user/views.py
> Jira [ON-90](https://orangenongjang.atlassian.net/browse/ON-90)
- html 태그를 사용하기 위해 기존의 `EmailMessage` 모듈 대신 `EmailMultiAlternatives`를 사용함.
- 메일 제목을 views.py에서 하드코딩하던 기존의 방식을 피하기 위해 text.py에서 처리함.
<br>
<br>
=> ON-90 [release] 가입 및 House 초대 메일 이쁘게 꾸미기

orange/src/components/Necessity/NecessityCounterButton/NecessityCounterButton.tsx, orange/src/store/actions/necessity/necessity.tsx
> Jira [ON-101](https://orangenongjang.atlassian.net/browse/ON-101)
- 기존의 `같은 이름의 Necessity가 존재합니다.` 에서 `이름과 설명이 같은 Necessity가 존재합니다.`로 메시지 변경
<br>
<br>
=> ON-101 [front] 중복된 생필품(이름 및 설명) 생성 및 수량이 0인 생필품 감소 버튼 클릭 시 에러 처리 방식 개선

nongjang/house/views.py, orange/.eslintrc.js, orange/src/containers/NecessityPage/NecessityPage.tsx, orange/src/store/actions/necessity/necessity.tsx, orange/src/store/reducers/necessity/necessity.tsx, orange/src/store/state.ts
related issues: https://orangenongjang.atlassian.net/browse/ON-80
- Create Place API 이후 GET House API를 호출함으로써 새로 추가된 Place를 포함해 Place의 array를 받아오는 식으로 처리되고 있었는데, GET House API가 호출되는 부분이 [createStatus에 의존하는 useEffect](https://github.com/gongmyeong-study/orangenongjang/blob/ed30666ad57ac2dfe8157a2dbbdc224e72de1de3/orange/src/containers/NecessityPage/NecessityPage.tsx#L40)에 있고, 이것이 호출되지 않는 고질적 문제([참고 Slack thread](https://gongmyeongstudy.slack.com/archives/C011CSJ7YBH/p1613817763002800?thread_ts=1613817628.002500&cid=C011CSJ7YBH))로 인해 추가된 Place를 새로 가져오지도 못하는 것이었음.
- 위에서 언급한, redux의 000Status에 의존하는 useEffect가 반복 수행시 호출되지 않는(예를 들어 반복 성공해서 createStatus가 "SUCCESS"로 그대로면 바뀌지 않은 것이므로) 문제는 고질적이고 다른 곳에도 퍼져있던 기존 이슈라 일단 냅두고, Create Place API의 response를 해당 House의 모든 Place array를 가져오는 것으로 바꾸어, 설령 modal은 …
=> ON-80 Place 반복 생성하면 추가된 Place가 바로 렌더링되지 않는 문제

orange/src/components/Necessity/NecessityCounterButton/NecessityCounterButton.tsx, orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> Jira [ON-32](https://orangenongjang.atlassian.net/browse/ON-32), [ON-46](https://orangenongjang.atlassian.net/browse/ON-46),  [ON-88](https://orangenongjang.atlassian.net/browse/ON-88)
- price와 count의 **하한값**은 0으로, **상한값**은 2^32 - 1인 4294967295로 설정함.
- Boundary 초과 시 API Call을 날려 Error Case를 확인하기보다 Front 단에서 price/count가 변경 불가하다는 **"올바른 양의 정수값을 입력해주세요!"** 메시지를 반환
<br>
<br>
=> ON-32, 46, 88 [front] 생필품 관련 modal에서 price/count 입력값 설정

orange/src/containers/TimelinePage/TimelinePage.tsx
related issues: https://orangenongjang.atlassian.net/browse/ON-106
- log가 로딩되고 있을 때 또는 실제로 없을 때 메시지가 뜸
=> ON-106 타임라인의 NecessityLog가 없을 때 메시지 채워주기

orange/src/components/House/HouseInviteModal/HouseInviteModal.tsx
- Jira [ON-125](https://orangenongjang.atlassian.net/browse/ON-125)
- 아래 문제 해결하였습니다. (실패 시 circular progress가 뜨지 않도록)
https://user-images.githubusercontent.com/46114393/108851638-020b5a80-7628-11eb-820d-c1ad4df3e60a.mp4
=> ON-125 [front] INVITE_HOUSE_FAILURE_LEADER일 때 isMailSended=false 처리하기

nongjang/nongjang/settings.py, orange/src/containers/InfoPage/InfoPage.css, orange/src/store/store.ts
- 실제 서비스시엔 debug=true는 바람직하지 않으며, 비효율적
- 필요하면 로컬에서 개발할 때만 수정해서 쓸 것
- 실제 서비스시에 모든 동작을 브라우저 콘솔에서 노출하는 것은 바람직하지 않으며, 비효율적
- 필요하면 로컬에서 개발할 때만 수정해서 쓸 것
- related threads: https://gongmyeongstudy.slack.com/archives/C011CSJ7YBH/p1614103880173600?thread_ts=1614098887.111700&cid=C011CSJ7YBH
=> ready for release

nongjang/user/text.py
> Jira [ON-135](https://orangenongjang.atlassian.net/browse/ON-135)
- 회원가입 인증 메일에 이름 및 이메일 정보를 수집한다는 다음의 내용을 추가
```
오렌지농장 은 다음과 같이 귀하의 개인정보를 수집, 이용합니다.
□ 개인정보의 수집 및 이용 목적
오렌지농장 이용자에 회원인증 메일 및 집 초대장 메일 전송
□ 수집하는 개인정보의 항목
필수정보 : 사용자 이름, E-Mail 주소
* 귀하는 위와 관련된 동의를 거부할 권리가 있으나, 필수정보 수집에 동의하지 않는 경우 오렌지농장 서비스 이용이 제한됩니다.
```
<br>
=> ON-135 [back] 회원가입 인증 메일에 이름 및 이메일 정보를 수집한다는 내용을 추가

orange/src/App.test.tsx, orange/src/containers/HousePage/HousePage.tsx, orange/src/tests/mocks.tsx
> Jira [ON-136](https://orangenongjang.atlassian.net/browse/ON-136)
- `reintroduceHouseStatus`, `renameHouseStatus`를 사용하여 수정 modal 밖의 페이지에도 연동되도록 수정.
<br>
- `getMockReducer`에 `mockHouseReducer` 추가
<br>
=> ON-136 [front] House Modal에서 집 이름/소개 수정 시 HouseList 최신화
